/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedRecruiterRouteImport } from './routes/_authenticated/recruiter'
import { Route as AuthenticatedStudentRouteImport } from './routes/_authenticated/student'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as AuthenticatedAdminApplicationsRouteImport } from './routes/_authenticated/admin.applications'
import { Route as AuthenticatedAdminAttentionRouteImport } from './routes/_authenticated/admin.attention'
import { Route as AuthenticatedAdminCompaniesRouteImport } from './routes/_authenticated/admin.companies'
import { Route as AuthenticatedAdminDocumentsRouteImport } from './routes/_authenticated/admin.documents'
import { Route as AuthenticatedAdminDrivesRouteImport } from './routes/_authenticated/admin.drives'
import { Route as AuthenticatedAdminEligibilityRouteImport } from './routes/_authenticated/admin.eligibility'
import { Route as AuthenticatedAdminInterviewsRouteImport } from './routes/_authenticated/admin.interviews'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin.notifications'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminStudentsRouteImport } from './routes/_authenticated/admin.students'
import { Route as AuthenticatedRecruiterIndexRouteImport } from './routes/_authenticated/recruiter.index'
import { Route as AuthenticatedRecruiterApplicationsRouteImport } from './routes/_authenticated/recruiter.applications'
import { Route as AuthenticatedRecruiterCompanyRouteImport } from './routes/_authenticated/recruiter.company'
import { Route as AuthenticatedRecruiterDashboardRouteImport } from './routes/_authenticated/recruiter.dashboard'
import { Route as AuthenticatedRecruiterDiscoverRouteImport } from './routes/_authenticated/recruiter.discover'
import { Route as AuthenticatedRecruiterInterviewsRouteImport } from './routes/_authenticated/recruiter.interviews'
import { Route as AuthenticatedRecruiterJobsRouteImport } from './routes/_authenticated/recruiter.jobs'
import { Route as AuthenticatedRecruiterNewJobRouteImport } from './routes/_authenticated/recruiter.new-job'
import { Route as AuthenticatedRecruiterOffersRouteImport } from './routes/_authenticated/recruiter.offers'
import { Route as AuthenticatedStudentIndexRouteImport } from './routes/_authenticated/student.index'
import { Route as AuthenticatedStudentApplicationsRouteImport } from './routes/_authenticated/student.applications'
import { Route as AuthenticatedStudentDrivesRouteImport } from './routes/_authenticated/student.drives'
import { Route as AuthenticatedStudentInsightsRouteImport } from './routes/_authenticated/student.insights'
import { Route as AuthenticatedStudentOpportunitiesRouteImport } from './routes/_authenticated/student.opportunities'
import { Route as AuthenticatedStudentProfileRouteImport } from './routes/_authenticated/student.profile'
import { Route as AuthenticatedRecruiterCandidateCandidateIdRouteImport } from './routes/_authenticated/recruiter.candidate.$candidateId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecruiterRoute = AuthenticatedRecruiterRouteImport.update({
  id: '/recruiter',
  path: '/recruiter',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentRoute = AuthenticatedStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminApplicationsRoute =
  AuthenticatedAdminApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAttentionRoute =
  AuthenticatedAdminAttentionRouteImport.update({
    id: '/attention',
    path: '/attention',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCompaniesRoute =
  AuthenticatedAdminCompaniesRouteImport.update({
    id: '/companies',
    path: '/companies',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDocumentsRoute =
  AuthenticatedAdminDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDrivesRoute =
  AuthenticatedAdminDrivesRouteImport.update({
    id: '/drives',
    path: '/drives',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEligibilityRoute =
  AuthenticatedAdminEligibilityRouteImport.update({
    id: '/eligibility',
    path: '/eligibility',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInterviewsRoute =
  AuthenticatedAdminInterviewsRouteImport.update({
    id: '/interviews',
    path: '/interviews',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStudentsRoute =
  AuthenticatedAdminStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedRecruiterIndexRoute =
  AuthenticatedRecruiterIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRecruiterRoute,
  } as any)
const AuthenticatedRecruiterApplicationsRoute =
  AuthenticatedRecruiterApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedRecruiterRoute,
  } as any)
const AuthenticatedRecruiterCompanyRoute =
  AuthenticatedRecruiterCompanyRouteImport.update({
    id: '/company',
    path: '/company',
    getParentRoute: () => AuthenticatedRecruiterRoute,
  } as any)
const AuthenticatedRecruiterDashboardRoute =
  AuthenticatedRecruiterDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRecruiterRoute,
  } as any)
const AuthenticatedRecruiterDiscoverRoute =
  AuthenticatedRecruiterDiscoverRouteImport.update({
    id: '/discover',
    path: '/discover',
    getParentRoute: () => AuthenticatedRecruiterRoute,
  } as any)
const AuthenticatedRecruiterInterviewsRoute =
  AuthenticatedRecruiterInterviewsRouteImport.update({
    id: '/interviews',
    path: '/interviews',
    getParentRoute: () => AuthenticatedRecruiterRoute,
  } as any)
const AuthenticatedRecruiterJobsRoute =
  AuthenticatedRecruiterJobsRouteImport.update({
    id: '/jobs',
    path: '/jobs',
    getParentRoute: () => AuthenticatedRecruiterRoute,
  } as any)
const AuthenticatedRecruiterNewJobRoute =
  AuthenticatedRecruiterNewJobRouteImport.update({
    id: '/new-job',
    path: '/new-job',
    getParentRoute: () => AuthenticatedRecruiterRoute,
  } as any)
const AuthenticatedRecruiterOffersRoute =
  AuthenticatedRecruiterOffersRouteImport.update({
    id: '/offers',
    path: '/offers',
    getParentRoute: () => AuthenticatedRecruiterRoute,
  } as any)
const AuthenticatedStudentIndexRoute =
  AuthenticatedStudentIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentApplicationsRoute =
  AuthenticatedStudentApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentDrivesRoute =
  AuthenticatedStudentDrivesRouteImport.update({
    id: '/drives',
    path: '/drives',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentInsightsRoute =
  AuthenticatedStudentInsightsRouteImport.update({
    id: '/insights',
    path: '/insights',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentOpportunitiesRoute =
  AuthenticatedStudentOpportunitiesRouteImport.update({
    id: '/opportunities',
    path: '/opportunities',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentProfileRoute =
  AuthenticatedStudentProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedRecruiterCandidateCandidateIdRoute =
  AuthenticatedRecruiterCandidateCandidateIdRouteImport.update({
    id: '/candidate/$candidateId',
    path: '/candidate/$candidateId',
    getParentRoute: () => AuthenticatedRecruiterRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/recruiter': typeof AuthenticatedRecruiterRouteWithChildren
  '/student': typeof AuthenticatedStudentRouteWithChildren
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/applications': typeof AuthenticatedAdminApplicationsRoute
  '/admin/attention': typeof AuthenticatedAdminAttentionRoute
  '/admin/companies': typeof AuthenticatedAdminCompaniesRoute
  '/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/admin/drives': typeof AuthenticatedAdminDrivesRoute
  '/admin/eligibility': typeof AuthenticatedAdminEligibilityRoute
  '/admin/interviews': typeof AuthenticatedAdminInterviewsRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/recruiter/applications': typeof AuthenticatedRecruiterApplicationsRoute
  '/recruiter/company': typeof AuthenticatedRecruiterCompanyRoute
  '/recruiter/dashboard': typeof AuthenticatedRecruiterDashboardRoute
  '/recruiter/discover': typeof AuthenticatedRecruiterDiscoverRoute
  '/recruiter/interviews': typeof AuthenticatedRecruiterInterviewsRoute
  '/recruiter/jobs': typeof AuthenticatedRecruiterJobsRoute
  '/recruiter/new-job': typeof AuthenticatedRecruiterNewJobRoute
  '/recruiter/offers': typeof AuthenticatedRecruiterOffersRoute
  '/student/applications': typeof AuthenticatedStudentApplicationsRoute
  '/student/drives': typeof AuthenticatedStudentDrivesRoute
  '/student/insights': typeof AuthenticatedStudentInsightsRoute
  '/student/opportunities': typeof AuthenticatedStudentOpportunitiesRoute
  '/student/profile': typeof AuthenticatedStudentProfileRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/recruiter/': typeof AuthenticatedRecruiterIndexRoute
  '/student/': typeof AuthenticatedStudentIndexRoute
  '/recruiter/candidate/$candidateId': typeof AuthenticatedRecruiterCandidateCandidateIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/applications': typeof AuthenticatedAdminApplicationsRoute
  '/admin/attention': typeof AuthenticatedAdminAttentionRoute
  '/admin/companies': typeof AuthenticatedAdminCompaniesRoute
  '/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/admin/drives': typeof AuthenticatedAdminDrivesRoute
  '/admin/eligibility': typeof AuthenticatedAdminEligibilityRoute
  '/admin/interviews': typeof AuthenticatedAdminInterviewsRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/recruiter/applications': typeof AuthenticatedRecruiterApplicationsRoute
  '/recruiter/company': typeof AuthenticatedRecruiterCompanyRoute
  '/recruiter/dashboard': typeof AuthenticatedRecruiterDashboardRoute
  '/recruiter/discover': typeof AuthenticatedRecruiterDiscoverRoute
  '/recruiter/interviews': typeof AuthenticatedRecruiterInterviewsRoute
  '/recruiter/jobs': typeof AuthenticatedRecruiterJobsRoute
  '/recruiter/new-job': typeof AuthenticatedRecruiterNewJobRoute
  '/recruiter/offers': typeof AuthenticatedRecruiterOffersRoute
  '/student/applications': typeof AuthenticatedStudentApplicationsRoute
  '/student/drives': typeof AuthenticatedStudentDrivesRoute
  '/student/insights': typeof AuthenticatedStudentInsightsRoute
  '/student/opportunities': typeof AuthenticatedStudentOpportunitiesRoute
  '/student/profile': typeof AuthenticatedStudentProfileRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/recruiter': typeof AuthenticatedRecruiterIndexRoute
  '/student': typeof AuthenticatedStudentIndexRoute
  '/recruiter/candidate/$candidateId': typeof AuthenticatedRecruiterCandidateCandidateIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/recruiter': typeof AuthenticatedRecruiterRouteWithChildren
  '/_authenticated/student': typeof AuthenticatedStudentRouteWithChildren
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/applications': typeof AuthenticatedAdminApplicationsRoute
  '/_authenticated/admin/attention': typeof AuthenticatedAdminAttentionRoute
  '/_authenticated/admin/companies': typeof AuthenticatedAdminCompaniesRoute
  '/_authenticated/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/_authenticated/admin/drives': typeof AuthenticatedAdminDrivesRoute
  '/_authenticated/admin/eligibility': typeof AuthenticatedAdminEligibilityRoute
  '/_authenticated/admin/interviews': typeof AuthenticatedAdminInterviewsRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/_authenticated/recruiter/applications': typeof AuthenticatedRecruiterApplicationsRoute
  '/_authenticated/recruiter/company': typeof AuthenticatedRecruiterCompanyRoute
  '/_authenticated/recruiter/dashboard': typeof AuthenticatedRecruiterDashboardRoute
  '/_authenticated/recruiter/discover': typeof AuthenticatedRecruiterDiscoverRoute
  '/_authenticated/recruiter/interviews': typeof AuthenticatedRecruiterInterviewsRoute
  '/_authenticated/recruiter/jobs': typeof AuthenticatedRecruiterJobsRoute
  '/_authenticated/recruiter/new-job': typeof AuthenticatedRecruiterNewJobRoute
  '/_authenticated/recruiter/offers': typeof AuthenticatedRecruiterOffersRoute
  '/_authenticated/student/applications': typeof AuthenticatedStudentApplicationsRoute
  '/_authenticated/student/drives': typeof AuthenticatedStudentDrivesRoute
  '/_authenticated/student/insights': typeof AuthenticatedStudentInsightsRoute
  '/_authenticated/student/opportunities': typeof AuthenticatedStudentOpportunitiesRoute
  '/_authenticated/student/profile': typeof AuthenticatedStudentProfileRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/recruiter/': typeof AuthenticatedRecruiterIndexRoute
  '/_authenticated/student/': typeof AuthenticatedStudentIndexRoute
  '/_authenticated/recruiter/candidate/$candidateId': typeof AuthenticatedRecruiterCandidateCandidateIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/dashboard'
    | '/recruiter'
    | '/student'
    | '/admin/analytics'
    | '/admin/applications'
    | '/admin/attention'
    | '/admin/companies'
    | '/admin/documents'
    | '/admin/drives'
    | '/admin/eligibility'
    | '/admin/interviews'
    | '/admin/notifications'
    | '/admin/settings'
    | '/admin/students'
    | '/recruiter/applications'
    | '/recruiter/company'
    | '/recruiter/dashboard'
    | '/recruiter/discover'
    | '/recruiter/interviews'
    | '/recruiter/jobs'
    | '/recruiter/new-job'
    | '/recruiter/offers'
    | '/student/applications'
    | '/student/drives'
    | '/student/insights'
    | '/student/opportunities'
    | '/student/profile'
    | '/admin/'
    | '/recruiter/'
    | '/student/'
    | '/recruiter/candidate/$candidateId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/admin/analytics'
    | '/admin/applications'
    | '/admin/attention'
    | '/admin/companies'
    | '/admin/documents'
    | '/admin/drives'
    | '/admin/eligibility'
    | '/admin/interviews'
    | '/admin/notifications'
    | '/admin/settings'
    | '/admin/students'
    | '/recruiter/applications'
    | '/recruiter/company'
    | '/recruiter/dashboard'
    | '/recruiter/discover'
    | '/recruiter/interviews'
    | '/recruiter/jobs'
    | '/recruiter/new-job'
    | '/recruiter/offers'
    | '/student/applications'
    | '/student/drives'
    | '/student/insights'
    | '/student/opportunities'
    | '/student/profile'
    | '/admin'
    | '/recruiter'
    | '/student'
    | '/recruiter/candidate/$candidateId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/recruiter'
    | '/_authenticated/student'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/applications'
    | '/_authenticated/admin/attention'
    | '/_authenticated/admin/companies'
    | '/_authenticated/admin/documents'
    | '/_authenticated/admin/drives'
    | '/_authenticated/admin/eligibility'
    | '/_authenticated/admin/interviews'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/students'
    | '/_authenticated/recruiter/applications'
    | '/_authenticated/recruiter/company'
    | '/_authenticated/recruiter/dashboard'
    | '/_authenticated/recruiter/discover'
    | '/_authenticated/recruiter/interviews'
    | '/_authenticated/recruiter/jobs'
    | '/_authenticated/recruiter/new-job'
    | '/_authenticated/recruiter/offers'
    | '/_authenticated/student/applications'
    | '/_authenticated/student/drives'
    | '/_authenticated/student/insights'
    | '/_authenticated/student/opportunities'
    | '/_authenticated/student/profile'
    | '/_authenticated/admin/'
    | '/_authenticated/recruiter/'
    | '/_authenticated/student/'
    | '/_authenticated/recruiter/candidate/$candidateId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recruiter': {
      id: '/_authenticated/recruiter'
      path: '/recruiter'
      fullPath: '/recruiter'
      preLoaderRoute: typeof AuthenticatedRecruiterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student': {
      id: '/_authenticated/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof AuthenticatedStudentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/applications': {
      id: '/_authenticated/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AuthenticatedAdminApplicationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/attention': {
      id: '/_authenticated/admin/attention'
      path: '/attention'
      fullPath: '/admin/attention'
      preLoaderRoute: typeof AuthenticatedAdminAttentionRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/companies': {
      id: '/_authenticated/admin/companies'
      path: '/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AuthenticatedAdminCompaniesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/documents': {
      id: '/_authenticated/admin/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AuthenticatedAdminDocumentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/drives': {
      id: '/_authenticated/admin/drives'
      path: '/drives'
      fullPath: '/admin/drives'
      preLoaderRoute: typeof AuthenticatedAdminDrivesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/eligibility': {
      id: '/_authenticated/admin/eligibility'
      path: '/eligibility'
      fullPath: '/admin/eligibility'
      preLoaderRoute: typeof AuthenticatedAdminEligibilityRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/interviews': {
      id: '/_authenticated/admin/interviews'
      path: '/interviews'
      fullPath: '/admin/interviews'
      preLoaderRoute: typeof AuthenticatedAdminInterviewsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/students': {
      id: '/_authenticated/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AuthenticatedAdminStudentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/recruiter/': {
      id: '/_authenticated/recruiter/'
      path: '/'
      fullPath: '/recruiter/'
      preLoaderRoute: typeof AuthenticatedRecruiterIndexRouteImport
      parentRoute: typeof AuthenticatedRecruiterRoute
    }
    '/_authenticated/recruiter/applications': {
      id: '/_authenticated/recruiter/applications'
      path: '/applications'
      fullPath: '/recruiter/applications'
      preLoaderRoute: typeof AuthenticatedRecruiterApplicationsRouteImport
      parentRoute: typeof AuthenticatedRecruiterRoute
    }
    '/_authenticated/recruiter/company': {
      id: '/_authenticated/recruiter/company'
      path: '/company'
      fullPath: '/recruiter/company'
      preLoaderRoute: typeof AuthenticatedRecruiterCompanyRouteImport
      parentRoute: typeof AuthenticatedRecruiterRoute
    }
    '/_authenticated/recruiter/dashboard': {
      id: '/_authenticated/recruiter/dashboard'
      path: '/dashboard'
      fullPath: '/recruiter/dashboard'
      preLoaderRoute: typeof AuthenticatedRecruiterDashboardRouteImport
      parentRoute: typeof AuthenticatedRecruiterRoute
    }
    '/_authenticated/recruiter/discover': {
      id: '/_authenticated/recruiter/discover'
      path: '/discover'
      fullPath: '/recruiter/discover'
      preLoaderRoute: typeof AuthenticatedRecruiterDiscoverRouteImport
      parentRoute: typeof AuthenticatedRecruiterRoute
    }
    '/_authenticated/recruiter/interviews': {
      id: '/_authenticated/recruiter/interviews'
      path: '/interviews'
      fullPath: '/recruiter/interviews'
      preLoaderRoute: typeof AuthenticatedRecruiterInterviewsRouteImport
      parentRoute: typeof AuthenticatedRecruiterRoute
    }
    '/_authenticated/recruiter/jobs': {
      id: '/_authenticated/recruiter/jobs'
      path: '/jobs'
      fullPath: '/recruiter/jobs'
      preLoaderRoute: typeof AuthenticatedRecruiterJobsRouteImport
      parentRoute: typeof AuthenticatedRecruiterRoute
    }
    '/_authenticated/recruiter/new-job': {
      id: '/_authenticated/recruiter/new-job'
      path: '/new-job'
      fullPath: '/recruiter/new-job'
      preLoaderRoute: typeof AuthenticatedRecruiterNewJobRouteImport
      parentRoute: typeof AuthenticatedRecruiterRoute
    }
    '/_authenticated/recruiter/offers': {
      id: '/_authenticated/recruiter/offers'
      path: '/offers'
      fullPath: '/recruiter/offers'
      preLoaderRoute: typeof AuthenticatedRecruiterOffersRouteImport
      parentRoute: typeof AuthenticatedRecruiterRoute
    }
    '/_authenticated/student/': {
      id: '/_authenticated/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof AuthenticatedStudentIndexRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/applications': {
      id: '/_authenticated/student/applications'
      path: '/applications'
      fullPath: '/student/applications'
      preLoaderRoute: typeof AuthenticatedStudentApplicationsRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/drives': {
      id: '/_authenticated/student/drives'
      path: '/drives'
      fullPath: '/student/drives'
      preLoaderRoute: typeof AuthenticatedStudentDrivesRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/insights': {
      id: '/_authenticated/student/insights'
      path: '/insights'
      fullPath: '/student/insights'
      preLoaderRoute: typeof AuthenticatedStudentInsightsRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/opportunities': {
      id: '/_authenticated/student/opportunities'
      path: '/opportunities'
      fullPath: '/student/opportunities'
      preLoaderRoute: typeof AuthenticatedStudentOpportunitiesRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/profile': {
      id: '/_authenticated/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof AuthenticatedStudentProfileRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/recruiter/candidate/$candidateId': {
      id: '/_authenticated/recruiter/candidate/$candidateId'
      path: '/candidate/$candidateId'
      fullPath: '/recruiter/candidate/$candidateId'
      preLoaderRoute: typeof AuthenticatedRecruiterCandidateCandidateIdRouteImport
      parentRoute: typeof AuthenticatedRecruiterRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminApplicationsRoute: typeof AuthenticatedAdminApplicationsRoute
  AuthenticatedAdminAttentionRoute: typeof AuthenticatedAdminAttentionRoute
  AuthenticatedAdminCompaniesRoute: typeof AuthenticatedAdminCompaniesRoute
  AuthenticatedAdminDocumentsRoute: typeof AuthenticatedAdminDocumentsRoute
  AuthenticatedAdminDrivesRoute: typeof AuthenticatedAdminDrivesRoute
  AuthenticatedAdminEligibilityRoute: typeof AuthenticatedAdminEligibilityRoute
  AuthenticatedAdminInterviewsRoute: typeof AuthenticatedAdminInterviewsRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminStudentsRoute: typeof AuthenticatedAdminStudentsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminApplicationsRoute: AuthenticatedAdminApplicationsRoute,
  AuthenticatedAdminAttentionRoute: AuthenticatedAdminAttentionRoute,
  AuthenticatedAdminCompaniesRoute: AuthenticatedAdminCompaniesRoute,
  AuthenticatedAdminDocumentsRoute: AuthenticatedAdminDocumentsRoute,
  AuthenticatedAdminDrivesRoute: AuthenticatedAdminDrivesRoute,
  AuthenticatedAdminEligibilityRoute: AuthenticatedAdminEligibilityRoute,
  AuthenticatedAdminInterviewsRoute: AuthenticatedAdminInterviewsRoute,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminStudentsRoute: AuthenticatedAdminStudentsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRecruiterRouteChildren {
  AuthenticatedRecruiterApplicationsRoute: typeof AuthenticatedRecruiterApplicationsRoute
  AuthenticatedRecruiterCompanyRoute: typeof AuthenticatedRecruiterCompanyRoute
  AuthenticatedRecruiterDashboardRoute: typeof AuthenticatedRecruiterDashboardRoute
  AuthenticatedRecruiterDiscoverRoute: typeof AuthenticatedRecruiterDiscoverRoute
  AuthenticatedRecruiterInterviewsRoute: typeof AuthenticatedRecruiterInterviewsRoute
  AuthenticatedRecruiterJobsRoute: typeof AuthenticatedRecruiterJobsRoute
  AuthenticatedRecruiterNewJobRoute: typeof AuthenticatedRecruiterNewJobRoute
  AuthenticatedRecruiterOffersRoute: typeof AuthenticatedRecruiterOffersRoute
  AuthenticatedRecruiterIndexRoute: typeof AuthenticatedRecruiterIndexRoute
  AuthenticatedRecruiterCandidateCandidateIdRoute: typeof AuthenticatedRecruiterCandidateCandidateIdRoute
}

const AuthenticatedRecruiterRouteChildren: AuthenticatedRecruiterRouteChildren =
  {
    AuthenticatedRecruiterApplicationsRoute:
      AuthenticatedRecruiterApplicationsRoute,
    AuthenticatedRecruiterCompanyRoute: AuthenticatedRecruiterCompanyRoute,
    AuthenticatedRecruiterDashboardRoute: AuthenticatedRecruiterDashboardRoute,
    AuthenticatedRecruiterDiscoverRoute: AuthenticatedRecruiterDiscoverRoute,
    AuthenticatedRecruiterInterviewsRoute:
      AuthenticatedRecruiterInterviewsRoute,
    AuthenticatedRecruiterJobsRoute: AuthenticatedRecruiterJobsRoute,
    AuthenticatedRecruiterNewJobRoute: AuthenticatedRecruiterNewJobRoute,
    AuthenticatedRecruiterOffersRoute: AuthenticatedRecruiterOffersRoute,
    AuthenticatedRecruiterIndexRoute: AuthenticatedRecruiterIndexRoute,
    AuthenticatedRecruiterCandidateCandidateIdRoute:
      AuthenticatedRecruiterCandidateCandidateIdRoute,
  }

const AuthenticatedRecruiterRouteWithChildren =
  AuthenticatedRecruiterRoute._addFileChildren(
    AuthenticatedRecruiterRouteChildren,
  )

interface AuthenticatedStudentRouteChildren {
  AuthenticatedStudentApplicationsRoute: typeof AuthenticatedStudentApplicationsRoute
  AuthenticatedStudentDrivesRoute: typeof AuthenticatedStudentDrivesRoute
  AuthenticatedStudentInsightsRoute: typeof AuthenticatedStudentInsightsRoute
  AuthenticatedStudentOpportunitiesRoute: typeof AuthenticatedStudentOpportunitiesRoute
  AuthenticatedStudentProfileRoute: typeof AuthenticatedStudentProfileRoute
  AuthenticatedStudentIndexRoute: typeof AuthenticatedStudentIndexRoute
}

const AuthenticatedStudentRouteChildren: AuthenticatedStudentRouteChildren = {
  AuthenticatedStudentApplicationsRoute: AuthenticatedStudentApplicationsRoute,
  AuthenticatedStudentDrivesRoute: AuthenticatedStudentDrivesRoute,
  AuthenticatedStudentInsightsRoute: AuthenticatedStudentInsightsRoute,
  AuthenticatedStudentOpportunitiesRoute:
    AuthenticatedStudentOpportunitiesRoute,
  AuthenticatedStudentProfileRoute: AuthenticatedStudentProfileRoute,
  AuthenticatedStudentIndexRoute: AuthenticatedStudentIndexRoute,
}

const AuthenticatedStudentRouteWithChildren =
  AuthenticatedStudentRoute._addFileChildren(AuthenticatedStudentRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedRecruiterRoute: typeof AuthenticatedRecruiterRouteWithChildren
  AuthenticatedStudentRoute: typeof AuthenticatedStudentRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedRecruiterRoute: AuthenticatedRecruiterRouteWithChildren,
  AuthenticatedStudentRoute: AuthenticatedStudentRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
